epochs: 5
batch_size: 8
learning_rate: 4e-4
weight_decay: 0.1 
sample_size: 512 # max number of tokens in sample
task_name: "2k" # the maximal sequence length of the Babilong samples
split: "qa1" # the Babilong split