epochs: 1
batch_size: 8
learning_rate: 4e-4
weight_decay: 0.1 
train_task_name: "2k" # the maximal sequence length of the Babilong samples
test_task_name: "2k"
train_split: "qa2" # the Babilong split
test_split: "qa1"

save_model: false
log_experiment: false