[project]
name = "hercules"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "einops>=0.8.1",
    "tensordict>=0.8.3",
    "wandb>=0.21.0",
]

[dependency-groups]
dev = [
]
