[project]
name = "jax-template"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "accelerate>=1.4.0",
    "bitsandbytes>=0.45.3",
    "black>=25.1.0",
    "colorama>=0.4.6",
    "datasets>=3.3.2",
    "einops>=0.8.1",
    "evaluate>=0.4.3",
    "hydra-core>=1.3.2",
    "isort>=6.0.1",
    "ruff>=0.9.8",
    "safetensors>=0.5.3",
    "tensordict>=0.7.2",
    "tokenizers>=0.21.0",
    "torch>=2.6.0",
    "transformers>=4.49.0",
]
