[project]
name = "hercules"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "accelerate>=1.4.0",
    "black>=25.1.0",
    "colorama>=0.4.6",
    "datasets>=3.3.2",
    "deepspeed>=0.17.1",
    "dotenv>=0.9.9",
    "einops>=0.8.1",
    "evaluate>=0.4.3",
    "hydra-core>=1.3.2",
    "ipykernel>=6.29.5",
    "ipython>=9.0.2",
    "isort>=6.0.1",
    "jupyter>=1.1.1",
    "matplotlib>=3.10.3",
    "nltk>=3.9.1",
    "optimum-quanto>=0.2.7",
    "ruff>=0.9.8",
    "safetensors>=0.5.3",
    "tensordict>=0.8.3",
    "tokenizers>=0.21.0",
    "torch>=2.6.0",
    "transformers>=4.49.0",
]

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
]

