services:
  mediawiki:
    image: mediawiki:1.39
    container_name: nethackwiki
    ports:
      - "8080:80"
    volumes:
      - ./dumps:/var/www/html/dumps:ro
      - ./data:/var/www/html/data
      - ./extensions:/var/www/html/extensions:ro
      - ./data/LocalSettings.php:/var/www/html/LocalSettings.php
      - ./sqlite:/var/www/data
    environment:
      MEDIAWIKI_DB_TYPE: sqlite
      MEDIAWIKI_DB_NAME: /var/www/data/nethackwiki.sqlite