experiment:
  name: "eduweb_pt"
  seed: 0
  epochs: 1
  eduweb_train_batch_size: 6
  eduweb_val_batch_size: 3
  babilong_test_batch_size: 4
  learning_rate: 4e-4
  weight_decay: 0.1

  num_train_samples: 1e4 # number of eduweb samples used for training
  num_val_samples: 2000 # number of samples used to compute the average validation loss
  num_eval: 100 # number of evaluations during training
  num_test_samples: 100
  max_train_seq_len: 2048 # maximum sequence length of training samples

  train_task_name: "2k" # the maximal sequence length of the Babilong samples
  test_task_name: "2k"
  train_splits: ~ # Babilong splits used in training
  test_splits: "all" # Babilong splits used in testing
  eval_with_generate: true # whether to evaluate the model performance with `.generate()`
  max_gen_tokens: 25 # maximum number of tokens generated for evaluation

  log_experiment: true # whether to log the experiment with wandb

  run_name: "TRAIN:Llama1B|FINETUNE|t1e4"

llama:
  llama_hf_path: "meta-llama/Llama-3.2-1B"
  
lora:
  lora_rank: 16        # The rank of the LoRA matrices.
  lora_alpha: 32       # The scaling factor for the LoRA weights.
  lora_dropout: 0.05
  lora_target_modules:
    - "q_proj"
    - "v_proj"
    - "k_proj"
    - "o_proj"
    - "gate_proj"
    - "down_proj"
    - "up_proj"